### Health
GET http://localhost:8080/api/health

###

### Register Admin
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "fullName": "Admin",
  "email": "admin@enterpriseai.local",
  "password": "Password123!"
}

###

### Register Maria
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "fullName": "Maria",
  "email": "maria@enterpriseai.local",
  "password": "Password123!"
}

###

### Register Duplicate User
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "fullName": "Admin Again",
  "email": "admin@enterpriseai.local",
  "password": "Password123!"
}

###

### Login Admin
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "admin@enterpriseai.local",
  "password": "Password123!"
}

###

### Login Maria
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "maria@enterpriseai.local",
  "password": "Password123!"
}



### Current User
GET http://localhost:8080/api/users/me
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBlbnRlcnByaXNlYWkubG9jYWwiLCJpYXQiOjE3ODE4NTc1MzksImV4cCI6MTc4MTk0MzkzOX0.vOKhQqZFgNx-72Gh564Ftpahx3TTNvc7AL_jcaUAIkStmc0dNASNPZeBJ-HDc6sHTeOFphbbg7RHmGJQCi8XNg

### Create Conversation
POST http://localhost:8080/api/conversations
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBlbnRlcnByaXNlYWkubG9jYWwiLCJpYXQiOjE3ODE4NTc1MzksImV4cCI6MTc4MTk0MzkzOX0.vOKhQqZFgNx-72Gh564Ftpahx3TTNvc7AL_jcaUAIkStmc0dNASNPZeBJ-HDc6sHTeOFphbbg7RHmGJQCi8XNg
Content-Type: application/json

{
  "title": "Primeira conversa"
}

###

### List Conversations
GET http://localhost:8080/api/conversations
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBlbnRlcnByaXNlYWkubG9jYWwiLCJpYXQiOjE3ODE4NTc1MzksImV4cCI6MTc4MTk0MzkzOX0.vOKhQqZFgNx-72Gh564Ftpahx3TTNvc7AL_jcaUAIkStmc0dNASNPZeBJ-HDc6sHTeOFphbbg7RHmGJQCi8XNg

### Send Message
POST http://localhost:8080/api/conversations/c7333485-a63d-408c-91c1-ae1dc463421e/messages
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBlbnRlcnByaXNlYWkubG9jYWwiLCJpYXQiOjE3ODE4NTc1MzksImV4cCI6MTc4MTk0MzkzOX0.vOKhQqZFgNx-72Gh564Ftpahx3TTNvc7AL_jcaUAIkStmc0dNASNPZeBJ-HDc6sHTeOFphbbg7RHmGJQCi8XNg
Content-Type: application/json

{
  "content": "Olá, como estás?"
}

###

### Get Messages
GET http://localhost:8080/api/conversations/c7333485-a63d-408c-91c1-ae1dc463421e/messages
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBlbnRlcnByaXNlYWkubG9jYWwiLCJpYXQiOjE3ODE4NTc1MzksImV4cCI6MTc4MTk0MzkzOX0.vOKhQqZFgNx-72Gh564Ftpahx3TTNvc7AL_jcaUAIkStmc0dNASNPZeBJ-HDc6sHTeOFphbbg7RHmGJQCi8XNg