@host = http://localhost:8080

@adminJwt = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBlbnRlcnByaXNlYWkubG9jYWwiLCJpYXQiOjE3ODIzMDkwNjcsImV4cCI6MTc4MjM5NTQ2N30.bL9-bPPE3h2h0h9ek1cNpdZadXtNC-BobQrdqnG6PZKRtd3ZeSHCLawFrgWssPPxVhScAK8NW6qKJqeHKr_8Zw
@mariaJwt = COLE_AQUI_O_TOKEN_DA_MARIA

@adminConversation = c5703f80-f58f-4cdd-a63c-35dd13e4d1c6


#######################################
# Documents
#######################################

### Upload Document
POST {{host}}/api/documents
Authorization: Bearer {{adminJwt}}
Content-Type: multipart/form-data; boundary=Boundary

--Boundary
Content-Disposition: form-data; name="file"; filename="test.txt"
Content-Type: text/plain

< ./files/test.txt
--Boundary--

###

### List Documents
GET {{host}}/api/documents
Authorization: Bearer {{adminJwt}}

### Initialize Qdrant Collection
POST {{host}}/api/vector/init