@host = http://localhost:8080

@adminJwt = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBlbnRlcnByaXNlYWkubG9jYWwiLCJpYXQiOjE3ODI3MjM2MDksImV4cCI6MTc4MjgxMDAwOX0.8PmCdgQqENUoe7DaN-x4A33pFVdygI6-SKiJFXZqsx5IhmxZNYNvpGqR6kBsi3B8xaL-ZFQGI_0eNPWiWDZq7A
@mariaJwt = COLE_AQUI_O_TOKEN_DA_MARIA

@adminConversation = c5703f80-f58f-4cdd-a63c-35dd13e4d1c6


#######################################
# Documents
#######################################

### Upload Document
POST {{host}}/api/documents
Authorization: Bearer {{adminJwt}}
Content-Type: multipart/form-data; boundary=Boundary

--Boundary
Content-Disposition: form-data; name="file"; filename="test.txt"
Content-Type: text/plain

< ./files/test.txt
--Boundary--

###

### List Documents
GET {{host}}/api/documents
Authorization: Bearer {{adminJwt}}

### Initialize Qdrant Collection
POST {{host}}/api/vector/init

### Vector Search
POST {{host}}/api/vector/search
Authorization: Bearer {{adminJwt}}
Content-Type: application/json

{
  "query": "Where are document embeddings stored?"
}

### RAG Ask
POST {{host}}/api/rag/ask
Authorization: Bearer {{adminJwt}}
Content-Type: application/json

{
  "question": "Where are document embeddings stored?"
}